const translations = {
    "en": {
        "appName": "Quest Bot",
        "points_balance": "Points Balance",
        "usdt_balance": "USDT Balance",
        "earn_points": "Earn Points",
        "invite_friends": "Invite Friends",
        "exchange_withdraw": "Exchange & Withdraw",
        "rewards_title": "Rewards",
        "hourly_reward_title": "Hourly Reward",
        "hourly_reward_desc": "Get 100 points every hour for free.",
        "claim_hourly_reward": "Claim Hourly Reward",
        "gift_code_title": "Gift Code",
        "gift_code_desc": "Enter the code you got from the channel.",
        "gift_code_placeholder": "Enter gift code",
        "redeem_code": "Redeem Code",
        "exchange_title": "Exchange & Withdraw",
        "your_current_balance": "Your Current Balance",
        "points": "Points",
        "convert_points_to_usdt": "Convert Points to USDT",
        "exchange_rate_info": "Current exchange rate:",
        "points_to_convert": "Points to convert",
        "enter_points_amount": "Enter points amount",
        "convert_button": "Convert",
        "withdraw_earnings": "Withdraw Earnings (USDT)",
        "wallet_address": "Wallet Address (USDT TRC20)",
        "enter_wallet_address": "Enter your wallet address",
        "amount_usdt": "Amount (USDT)",
        "min_10_usdt": "Minimum 10 USDT",
        "submit_withdrawal_request": "Submit Withdrawal Request",
        "earn_title": "Earn Points",
        "urgent_tasks": "🔥 Urgent Tasks",
        "daily_tasks": "Daily Tasks",
        "go": "Go",
        "completed": "Completed",
        "friends_title": "Invite Friends",
        "invite_and_earn": "Share the Bot with Friends!", // Changed
        "invite_desc": "Share the bot with your friends and help our community grow.", // Changed
        "invite_share_button": "Share Bot Link",
        "your_referrals": "Your Referrals",
        "referral_count_text": "You have invited",
        "friends_suffix": "friends.",
        "daily_reward_title": "Daily Reward",
        "daily_reward_desc": "Check in daily to earn valuable rewards.",
        "days_streak": "days streak",
        "claim_reward": "Claim Reward",
        "ok": "OK",
        "nav_exchange": "Exchange",
        "nav_rewards": "Rewards",
        "nav_home": "Home",
        "nav_friends": "Friends",
        "nav_earn": "Earn",
        "loading": "Loading...",
        "reward_ready": "Reward is Ready!",
        "ready_in": "Ready in",
        "congrats_points": "Congratulations! You received {points} points.",
        "error_occurred": "An error occurred. Please try again.",
        "code_invalid": "The gift code is invalid or has expired.",
        "enter_points_amount": "Please enter a valid amount of points.",
        "points_insufficient": "You don't have enough points.",
        "min_conversion_limit": "Minimum conversion is",
        "conversion_success": "were successfully converted to",
        "withdrawal_success": "Your withdrawal request has been submitted successfully.",
        "no_tasks_available": "No tasks available at the moment.",
        "task_completion_success": "Task completed! Reward has been added.",
        "task_verification_failed": "Task verification failed. Please try again.",
        "bot_share_text": "Check out this cool bot!" // New
    },
    "ar": {
        "appName": "بوت كويست",
        "points_balance": "رصيد النقاط",
        "usdt_balance": "رصيد الدولار",
        "earn_points": "اكسب النقاط",
        "invite_friends": "ادعُ الأصدقاء",
        "exchange_withdraw": "تحويل وسحب",
        "rewards_title": "المكافآت",
        "hourly_reward_title": "مكافأة كل ساعة",
        "hourly_reward_desc": "احصل على 100 نقطة كل ساعة مجاناً.",
        "claim_hourly_reward": "المطالبة بالمكافأة",
        "gift_code_title": "كود الهدية",
        "gift_code_desc": "أدخل الكود الذي حصلت عليه من القناة.",
        "gift_code_placeholder": "أدخل كود الهدية",
        "redeem_code": "تفعيل الكود",
        "exchange_title": "تحويل وسحب",
        "your_current_balance": "رصيدك الحالي",
        "points": "نقاط",
        "convert_points_to_usdt": "تحويل النقاط إلى USDT",
        "exchange_rate_info": "سعر الصرف الحالي:",
        "points_to_convert": "النقاط المراد تحويلها",
        "enter_points_amount": "أدخل كمية النقاط",
        "convert_button": "تحويل",
        "withdraw_earnings": "سحب الأرباح (USDT)",
        "wallet_address": "عنوان المحفظة (USDT TRC20)",
        "enter_wallet_address": "أدخل عنوان محفظتك",
        "amount_usdt": "المبلغ (USDT)",
        "min_10_usdt": "الحد الأدنى 10 USDT",
        "submit_withdrawal_request": "إرسال طلب السحب",
        "earn_title": "اكسب النقاط",
        "urgent_tasks": "🔥 مهام عاجلة",
        "daily_tasks": "المهام اليومية",
        "go": "إبدأ",
        "completed": "مكتمل",
        "friends_title": "دعوة الأصدقاء",
        "invite_and_earn": "شارك البوت مع أصدقائك!", // تم التغيير
        "invite_desc": "شارك البوت مع أصدقائك وساعد مجتمعنا على النمو.", // تم التغيير
        "invite_share_button": "مشاركة رابط البوت",
        "your_referrals": "إحالاتك",
        "referral_count_text": "لقد قمت بدعوة",
        "friends_suffix": "أصدقاء.",
        "daily_reward_title": "المكافأة اليومية",
        "daily_reward_desc": "سجل حضورك يومياً لتربح مكافآت قيمة.",
        "days_streak": "أيام متتالية",
        "claim_reward": "المطالبة بالمكافأة",
        "ok": "حسناً",
        "nav_exchange": "تحويل",
        "nav_rewards": "المكافآت",
        "nav_home": "الرئيسية",
        "nav_friends": "الأصدقاء",
        "nav_earn": "اكسب",
        "loading": "جاري التحميل...",
        "reward_ready": "المكافأة جاهزة!",
        "ready_in": "جاهز بعد",
        "congrats_points": "تهانينا! لقد حصلت على {points} نقاط.",
        "error_occurred": "حدث خطأ. يرجى المحاولة مرة أخرى.",
        "code_invalid": "كود الهدية غير صالح أو منتهي الصلاحية.",
        "enter_points_amount": "الرجاء إدخال كمية نقاط صالحة.",
        "points_insufficient": "ليس لديك نقاط كافية.",
        "min_conversion_limit": "الحد الأدنى للتحويل هو",
        "conversion_success": "تم تحويلها بنجاح إلى",
        "withdrawal_success": "تم إرسال طلب السحب الخاص بك بنجاح.",
        "no_tasks_available": "لا توجد مهام متاحة في الوقت الحالي.",
        "task_completion_success": "اكتملت المهمة! تمت إضافة المكافأة.",
        "task_verification_failed": "فشل التحقق من المهمة. حاول مرة أخرى.",
        "bot_share_text": "اكتشف هذا البوت الرائع!" // نص جديد
    }
};
